from PyQt5 import QtCore, QtGui, QtWidgets
import _sqlite3 as sq
import os


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(995, 482)
        MainWindow.setMinimumSize(QtCore.QSize(640, 480))
        MainWindow.setTabShape(QtWidgets.QTabWidget.Triangular)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.masterFrame = QtWidgets.QFrame(self.centralwidget)
        self.masterFrame.setGeometry(QtCore.QRect(-10, 0, 1011, 491))
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.masterFrame.sizePolicy().hasHeightForWidth())
        self.masterFrame.setSizePolicy(sizePolicy)
        self.masterFrame.setObjectName("masterFrame")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.masterFrame)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.masterLayout = QtWidgets.QVBoxLayout()
        self.masterLayout.setObjectName("masterLayout")
        self.topFrame = QtWidgets.QFrame(self.masterFrame)
        self.topFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.topFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.topFrame.setObjectName("topFrame")
        self.horizontalLayoutWidget = QtWidgets.QWidget(self.topFrame)
        self.horizontalLayoutWidget.setGeometry(QtCore.QRect(-1, -1, 981, 221))
        self.horizontalLayoutWidget.setObjectName("horizontalLayoutWidget")
        self.topDivision = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget)
        self.topDivision.setContentsMargins(10, 10, 10, 10)
        self.topDivision.setSpacing(10)
        self.topDivision.setObjectName("topDivision")
        self.todayFrame = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.todayFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.todayFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.todayFrame.setObjectName("todayFrame")
        self.todayWidget = QtWidgets.QWidget(self.todayFrame)
        self.todayWidget.setGeometry(QtCore.QRect(-1, -1, 311, 201))
        self.todayWidget.setObjectName("todayWidget")
        self.todayLabel = QtWidgets.QLabel(self.todayWidget)
        self.todayLabel.setGeometry(QtCore.QRect(120, 10, 51, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.todayLabel.setFont(font)
        self.todayLabel.setObjectName("todayLabel")
        self.todayTable = QtWidgets.QTableWidget(self.todayWidget)
        self.todayTable.setGeometry(QtCore.QRect(10, 70, 291, 120))
        self.todayTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.todayTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.todayTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.todayTable.setTextElideMode(QtCore.Qt.ElideRight)
        self.todayTable.setShowGrid(True)
        self.todayTable.setGridStyle(QtCore.Qt.SolidLine)
        self.todayTable.setColumnCount(1)
        self.todayTable.setObjectName("todayTable")
        self.todayTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.todayTable.setHorizontalHeaderItem(0, item)
        self.todayRecipe = QtWidgets.QLabel(self.todayWidget)
        self.todayRecipe.setGeometry(QtCore.QRect(20, 40, 131, 21))
        self.todayRecipe.setObjectName("todayRecipe")
        self.topDivision.addWidget(self.todayFrame)
        self.tommorowFrame = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.tommorowFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.tommorowFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.tommorowFrame.setObjectName("tommorowFrame")
        self.tommorowWidget = QtWidgets.QWidget(self.tommorowFrame)
        self.tommorowWidget.setGeometry(QtCore.QRect(0, 0, 311, 201))
        self.tommorowWidget.setObjectName("tommorowWidget")
        self.tommorowLabel = QtWidgets.QLabel(self.tommorowWidget)
        self.tommorowLabel.setGeometry(QtCore.QRect(120, 10, 91, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.tommorowLabel.setFont(font)
        self.tommorowLabel.setObjectName("tommorowLabel")
        self.tommorowRecipe = QtWidgets.QLabel(self.tommorowWidget)
        self.tommorowRecipe.setGeometry(QtCore.QRect(10, 40, 171, 21))
        self.tommorowRecipe.setObjectName("tommorowRecipe")
        self.tommorowTable = QtWidgets.QTableWidget(self.tommorowWidget)
        self.tommorowTable.setGeometry(QtCore.QRect(10, 70, 291, 120))
        self.tommorowTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.tommorowTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.tommorowTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.tommorowTable.setTextElideMode(QtCore.Qt.ElideRight)
        self.tommorowTable.setShowGrid(True)
        self.tommorowTable.setGridStyle(QtCore.Qt.SolidLine)
        self.tommorowTable.setColumnCount(1)
        self.tommorowTable.setObjectName("tommorowTable")
        self.tommorowTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.tommorowTable.setHorizontalHeaderItem(0, item)
        self.topDivision.addWidget(self.tommorowFrame)
        self.dayAfterFrame = QtWidgets.QFrame(self.horizontalLayoutWidget)
        self.dayAfterFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.dayAfterFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.dayAfterFrame.setObjectName("dayAfterFrame")
        self.dayAfterWidget = QtWidgets.QWidget(self.dayAfterFrame)
        self.dayAfterWidget.setGeometry(QtCore.QRect(-1, -1, 311, 201))
        self.dayAfterWidget.setObjectName("dayAfterWidget")
        self.dayAfterLabel = QtWidgets.QLabel(self.dayAfterWidget)
        self.dayAfterLabel.setGeometry(QtCore.QRect(80, 10, 181, 21))
        font = QtGui.QFont()
        font.setBold(True)
        font.setUnderline(True)
        font.setWeight(75)
        self.dayAfterLabel.setFont(font)
        self.dayAfterLabel.setObjectName("dayAfterLabel")
        self.dayAfterRecipe = QtWidgets.QLabel(self.dayAfterWidget)
        self.dayAfterRecipe.setGeometry(QtCore.QRect(10, 40, 251, 21))
        self.dayAfterRecipe.setObjectName("dayAfterRecipe")
        self.dayAfterTable = QtWidgets.QTableWidget(self.dayAfterWidget)
        self.dayAfterTable.setGeometry(QtCore.QRect(10, 70, 291, 120))
        self.dayAfterTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.dayAfterTable.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.dayAfterTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.dayAfterTable.setTextElideMode(QtCore.Qt.ElideRight)
        self.dayAfterTable.setShowGrid(True)
        self.dayAfterTable.setGridStyle(QtCore.Qt.SolidLine)
        self.dayAfterTable.setColumnCount(1)
        self.dayAfterTable.setObjectName("dayAfterTable")
        self.dayAfterTable.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.dayAfterTable.setHorizontalHeaderItem(0, item)
        self.topDivision.addWidget(self.dayAfterFrame)
        self.masterLayout.addWidget(self.topFrame)
        self.bottomFrame = QtWidgets.QFrame(self.masterFrame)
        self.bottomFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.bottomFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.bottomFrame.setObjectName("bottomFrame")
        self.horizontalLayoutWidget_2 = QtWidgets.QWidget(self.bottomFrame)
        self.horizontalLayoutWidget_2.setGeometry(QtCore.QRect(-1, -1, 981, 231))
        self.horizontalLayoutWidget_2.setObjectName("horizontalLayoutWidget_2")
        self.bottomDivision = QtWidgets.QHBoxLayout(self.horizontalLayoutWidget_2)
        self.bottomDivision.setContentsMargins(10, 10, 10, 10)
        self.bottomDivision.setSpacing(10)
        self.bottomDivision.setObjectName("bottomDivision")
        self.foodlListFrame = QtWidgets.QFrame(self.horizontalLayoutWidget_2)
        self.foodlListFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.foodlListFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.foodlListFrame.setObjectName("foodlListFrame")
        self.listEditFrame = QtWidgets.QFrame(self.foodlListFrame)
        self.listEditFrame.setEnabled(True)
        self.listEditFrame.setGeometry(QtCore.QRect(664, 0, 291, 211))
        self.listEditFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.listEditFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.listEditFrame.setObjectName("listEditFrame")
        self.editMenu = QtWidgets.QWidget(self.listEditFrame)
        self.editMenu.setGeometry(QtCore.QRect(10, 10, 271, 191))
        self.editMenu.setObjectName("editMenu")
        self.editorTab = QtWidgets.QTabWidget(self.editMenu)
        self.editorTab.setGeometry(QtCore.QRect(0, 0, 401, 191))
        self.editorTab.setFocusPolicy(QtCore.Qt.TabFocus)
        self.editorTab.setLayoutDirection(QtCore.Qt.LeftToRight)
        self.editorTab.setTabPosition(QtWidgets.QTabWidget.North)
        self.editorTab.setTabShape(QtWidgets.QTabWidget.Rounded)
        self.editorTab.setElideMode(QtCore.Qt.ElideNone)
        self.editorTab.setObjectName("editorTab")
        self.Add = QtWidgets.QWidget()
        self.Add.setCursor(QtGui.QCursor(QtCore.Qt.UpArrowCursor))
        self.Add.setObjectName("Add")
        self.itemAddLabel = QtWidgets.QLabel(self.Add)
        self.itemAddLabel.setGeometry(QtCore.QRect(10, 20, 80, 21))
        self.itemAddLabel.setObjectName("itemAddLabel")
        self.addItemBox = QtWidgets.QLineEdit(self.Add)
        self.addItemBox.setGeometry(QtCore.QRect(100, 10, 161, 29))
        self.addItemBox.setObjectName("addItemBox")
        self.quantityAddLabel_2 = QtWidgets.QLabel(self.Add)
        self.quantityAddLabel_2.setGeometry(QtCore.QRect(10, 60, 80, 21))
        self.quantityAddLabel_2.setObjectName("quantityAddLabel_2")
        self.addGramsBox = QtWidgets.QLineEdit(self.Add)
        self.addGramsBox.setGeometry(QtCore.QRect(102, 50, 161, 29))
        self.addGramsBox.setObjectName("addGramsBox")
        self.addItemButton = QtWidgets.QPushButton(self.Add, clicked=lambda: self.add_item())
        self.addItemButton.setGeometry(QtCore.QRect(80, 100, 106, 30))
        self.addItemButton.setDefault(False)
        self.addItemButton.setFlat(False)
        self.addItemButton.setObjectName("addItemButton")
        self.editorTab.addTab(self.Add, "")
        self.Edit = QtWidgets.QWidget()
        self.Edit.setObjectName("Edit")
        self.itemEditLabel = QtWidgets.QLabel(self.Edit)
        self.itemEditLabel.setGeometry(QtCore.QRect(10, 20, 80, 21))
        self.itemEditLabel.setObjectName("itemEditLabel")
        self.quantityEditLabel = QtWidgets.QLabel(self.Edit)
        self.quantityEditLabel.setGeometry(QtCore.QRect(10, 60, 80, 21))
        self.quantityEditLabel.setObjectName("quantityEditLabel")
        self.editFromPantry = QtWidgets.QListWidget(self.Edit)
        self.editFromPantry.setGeometry(QtCore.QRect(100, 10, 161, 31))
        self.editFromPantry.setTabKeyNavigation(True)
        self.editFromPantry.setProperty("showDropIndicator", True)
        self.editFromPantry.setAlternatingRowColors(True)
        self.editFromPantry.setProperty("isWrapping", False)
        self.editFromPantry.setUniformItemSizes(True)
        self.editFromPantry.setObjectName("editFromPantry")
        self.editGramsBox = QtWidgets.QLineEdit(self.Edit)
        self.editGramsBox.setGeometry(QtCore.QRect(100, 50, 161, 29))
        self.editGramsBox.setObjectName("editGramsBox")
        self.confirmChangeButton = QtWidgets.QPushButton(self.Edit)
        self.confirmChangeButton.setGeometry(QtCore.QRect(70, 100, 141, 30))
        self.confirmChangeButton.setDefault(False)
        self.confirmChangeButton.setFlat(False)
        self.confirmChangeButton.setObjectName("confirmChangeButton")
        self.editorTab.addTab(self.Edit, "")
        self.Remove = QtWidgets.QWidget()
        self.Remove.setObjectName("Remove")
        self.itemRemoveLabel = QtWidgets.QLabel(self.Remove)
        self.itemRemoveLabel.setGeometry(QtCore.QRect(10, 20, 80, 21))
        self.itemRemoveLabel.setObjectName("itemRemoveLabel")
        self.deleteFromPantry = QtWidgets.QListWidget(self.Remove)
        self.deleteFromPantry.setGeometry(QtCore.QRect(100, 10, 151, 31))
        self.deleteFromPantry.setTabKeyNavigation(True)
        self.deleteFromPantry.setProperty("showDropIndicator", True)
        self.deleteFromPantry.setAlternatingRowColors(True)
        self.deleteFromPantry.setProperty("isWrapping", False)
        self.deleteFromPantry.setUniformItemSizes(True)
        self.deleteFromPantry.setObjectName("deleteFromPantry")
        self.removeItemButton = QtWidgets.QPushButton(self.Remove)
        self.removeItemButton.setGeometry(QtCore.QRect(70, 90, 141, 30))
        self.removeItemButton.setDefault(False)
        self.removeItemButton.setFlat(False)
        self.removeItemButton.setObjectName("removeItemButton")
        self.editorTab.addTab(self.Remove, "")
        self.pantryTableFrame = QtWidgets.QFrame(self.foodlListFrame)
        self.pantryTableFrame.setGeometry(QtCore.QRect(339, 9, 321, 191))
        self.pantryTableFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.pantryTableFrame.setFrameShadow(QtWidgets.QFrame.Raised)

        self.pantryTableFrame.setObjectName("pantryTableFrame")
        self.pantryTable = QtWidgets.QTableWidget(self.pantryTableFrame)
        self.pantryTable.setGeometry(QtCore.QRect(10, 30, 301, 151))
        self.pantryTable.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.pantryTable.setEditTriggers(QtWidgets.QAbstractItemView.NoEditTriggers)
        self.pantryTable.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.pantryTable.setGridStyle(QtCore.Qt.SolidLine)
        self.pantryTable.setRowCount(0)
        self.pantryTable.setColumnCount(2)
        self.pantryTable.setObjectName("pantryTable")
        item = QtWidgets.QTableWidgetItem()
        self.pantryTable.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.pantryTable.setHorizontalHeaderItem(1, item)
        self.pantryTable.horizontalHeader().setCascadingSectionResizes(False)
        self.pantryLabel = QtWidgets.QLabel(self.pantryTableFrame)
        self.pantryLabel.setGeometry(QtCore.QRect(10, 10, 80, 21))
        self.pantryLabel.setObjectName("pantryLabel")
        self.selectedRecipeFrame = QtWidgets.QFrame(self.foodlListFrame)
        self.selectedRecipeFrame.setGeometry(QtCore.QRect(10, 10, 321, 191))
        self.selectedRecipeFrame.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.selectedRecipeFrame.setFrameShadow(QtWidgets.QFrame.Raised)
        self.selectedRecipeFrame.setObjectName("selectedRecipeFrame")
        self.pantryLabel_2 = QtWidgets.QLabel(self.selectedRecipeFrame)
        self.pantryLabel_2.setGeometry(QtCore.QRect(10, 10, 141, 21))
        self.pantryLabel_2.setObjectName("pantryLabel_2")
        self.todayTable_2 = QtWidgets.QTableWidget(self.selectedRecipeFrame)
        self.todayTable_2.setGeometry(QtCore.QRect(10, 40, 291, 141))
        self.todayTable_2.setVerticalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOn)
        self.todayTable_2.setHorizontalScrollBarPolicy(QtCore.Qt.ScrollBarAlwaysOff)
        self.todayTable_2.setSizeAdjustPolicy(QtWidgets.QAbstractScrollArea.AdjustToContents)
        self.todayTable_2.setTextElideMode(QtCore.Qt.ElideRight)
        self.todayTable_2.setShowGrid(True)
        self.todayTable_2.setGridStyle(QtCore.Qt.SolidLine)
        self.todayTable_2.setColumnCount(2)
        self.todayTable_2.setObjectName("todayTable_2")
        self.todayTable_2.setRowCount(0)
        item = QtWidgets.QTableWidgetItem()
        self.todayTable_2.setHorizontalHeaderItem(0, item)
        item = QtWidgets.QTableWidgetItem()
        self.todayTable_2.setHorizontalHeaderItem(1, item)
        self.bottomDivision.addWidget(self.foodlListFrame)
        self.masterLayout.addWidget(self.bottomFrame)
        self.verticalLayout_4.addLayout(self.masterLayout)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        self.editorTab.setCurrentIndex(1)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        MainWindow.setTabOrder(self.pantryTable, self.editorTab)

        self.update_pantry()

    def grab_all_pantry_items(self):
        records = self.run_query("SELECT registry.name FROM registry")
        return [data[0] for data in records if records]

    def run_query(self, query):
        db = sq.connect("/home/ioan/PycharmProjects/hackathon/src/pipeline/scran")
        c = db.cursor()
        c.execute(query)
        result = c.fetchall()
        db.close()
        return result

    def get_item_from_text(self):
        return self.addItemBox.text()

    def get_gram_from_text(self):
        return self.addGramsBox.text()

    def add_item(self):
        item = self.get_item_from_text()
        gram = self.get_gram_from_text()
        if item.isalpha() and gram.isnumeric():
            db = sq.connect("/home/ioan/PycharmProjects/hackathon/src/pipeline/scran")
            c = db.cursor()
            c.execute("INSERT INTO main.pantry VALUES (:name,:mass)", {'name': item, 'mass': gram})
            db.close()
        self.update_pantry()

    def update_pantry(self):
        for i, name in enumerate(self.grab_all_pantry_items()):
            self.pantryTable.setRowCount(i + 1)
            item_name = QtWidgets.QTableWidgetItem(name)
            item_name.setText(name)
            self.pantryTable.setItem(i, 0, item_name)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "SCRAN"))
        self.todayLabel.setText(_translate("MainWindow", "Today"))
        item = self.todayTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Recipes:"))
        self.todayRecipe.setText(_translate("MainWindow", "Today\'s Recipes"))
        self.tommorowLabel.setText(_translate("MainWindow", "Tommrow"))
        self.tommorowRecipe.setText(_translate("MainWindow", "Tommorow\'s Recipes"))
        item = self.tommorowTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Recipes:"))
        self.dayAfterLabel.setText(_translate("MainWindow", "Day After Tommorow"))
        self.dayAfterRecipe.setText(_translate("MainWindow", "Day After Tommorows Recipes"))
        item = self.dayAfterTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "Recipes:"))
        self.itemAddLabel.setText(_translate("MainWindow", "Item"))
        self.addItemBox.setPlaceholderText(_translate("MainWindow", "Enter an Item"))
        self.quantityAddLabel_2.setText(_translate("MainWindow", "Quantity"))
        self.addGramsBox.setPlaceholderText(_translate("MainWindow", "Enter grams"))
        self.addItemButton.setText(_translate("MainWindow", "Add Item"))
        self.editorTab.setTabText(self.editorTab.indexOf(self.Add), _translate("MainWindow", "Add"))
        self.itemEditLabel.setText(_translate("MainWindow", "Item"))
        self.quantityEditLabel.setText(_translate("MainWindow", "Quantity"))
        self.editFromPantry.setSortingEnabled(True)
        self.editGramsBox.setPlaceholderText(_translate("MainWindow", "Enter grams"))
        self.confirmChangeButton.setText(_translate("MainWindow", "Confirm Change"))
        self.editorTab.setTabText(self.editorTab.indexOf(self.Edit), _translate("MainWindow", "Edit"))
        self.itemRemoveLabel.setText(_translate("MainWindow", "Item"))
        self.deleteFromPantry.setSortingEnabled(True)
        self.removeItemButton.setText(_translate("MainWindow", "Remove Item"))
        self.editorTab.setTabText(self.editorTab.indexOf(self.Remove), _translate("MainWindow", "Remove"))
        self.pantryTable.setSortingEnabled(True)
        item = self.pantryTable.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ITEM"))
        item = self.pantryTable.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "AMOUNT"))
        self.pantryLabel.setText(_translate("MainWindow",
                                            "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Pantry</span></p></body></html>"))
        self.pantryLabel_2.setText(_translate("MainWindow",
                                              "<html><head/><body><p><span style=\" font-weight:600; text-decoration: underline;\">Selected Recipe</span></p></body></html>"))
        item = self.todayTable_2.horizontalHeaderItem(0)
        item.setText(_translate("MainWindow", "ITEM"))
        item = self.todayTable_2.horizontalHeaderItem(1)
        item.setText(_translate("MainWindow", "AMOUNT"))


if __name__ == "__main__":
    import sys

    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
